### PR TITLE
fix indentations

### PR DESCRIPTION
**Pull request by earthfail**
fix indentations in clojure files based on standarts

### CODE REVIEW

**Comment by leios** [comment]
Great! Thanks for this!

**Comment by Butt4cak3** [comment]
@earthfail Did you notice that there are very old and outdated commits in your pull request? You should probably clean that up, because it will only grow larger over time. I can help you if there's some way we can chat.

**Comment by leios** [comment]
Yeah, my bad. I should have left this open for a bit to talk about git.

**Comment by earthfail** [comment]
@Butt4cak3  I didn't know how to remove them so there they are here forever

**Comment by julianschacherpp** [comment]
@earthfail You can join our Discord guild (server), if you want. There we talk about all kinds of stuff and discuss things regarding the AAA. Here's the link: https://discord.gg/XRxWqdq

**Pull request merged**
