### PR TITLE
Adding C++ euler

### PR DESCRIPTION
**Pull request by Gathros**

### CODE REVIEW

**Comment by ubsan** [comment]
I don't like how unclear the output is; I'm submitting a PR.

**Comment by Gathros** [comment]
Thanks @ubsan.

**Comment by ubsan** [comment]
We should also seriously come up with a convention for include ordering. After this is merged, I think I'll go through all the C++ files and order the includes in alphabetic order.

**Comment by leios** [comment]
@ubsan what do you mean by include ordering? Are you talking about the `#include <>` statements?

Sorry, I'm just drawing a blank right now.

**Comment by ubsan** [comment]
@leios right, the ordering of the include statements.

**Comment by Gathros** [comment]
Just merge this PR @leios.

**Comment by leios** [comment]
Alright, this has been merged.

**Pull request merged**
