### PR TITLE
Rust/Haskell/OCaml/C++ negative nums

### PR DESCRIPTION
**Pull request by ubsan**
also standardize C++ style

### CODE REVIEW

**Comment by julianschacherpp** [comment]
I'am not quite sure, if it's better to use a -= b instead of a = a - b

**Comment by leios** [comment]
I think we are overthinking this. The `-=` is standard / I am not worried about that one. I just don't like the `auto` and `uint64_t`

All other changes are great and I really appreciate it! =)

**Comment by ubsan** [comment]
@leios I'm not sure what issue you have with `auto` - that's... how C++ is written. You can write C++ like C with classes, but then it's not really C++.

**Comment by leios** [comment]
Wow you are quick. Thanks! =)

**Pull request merged**
