### PR TITLE
Sorting algorithms in JavaScript

### PR DESCRIPTION
**Pull request by Butt4cak3**
Once merged, this pull request will add JavaScript examples for the arguably two most important algorithm in the archive: Bubble Sort and Bogo Sort.

### CODE REVIEW

**Comment by Butt4cak3** [comment]
One thing I want to mention is that the `shuffle` function that's used in the Bogo Sort implementation does not show up in the book. I left it out to keep the code closer to the other implementations, but I left it in the source file to give people the possibility to use the code more easily.

**Comment by leios** [comment]
You think we should leave a comment telling them where the `shuffle()` function is?

**Comment by Butt4cak3** [comment]
Good idea. I'll add one.

**Comment by leios** [comment]
Or I can add it and merge it now

**Comment by Butt4cak3** [comment]
Go ahead. I'm on mobile at the moment.

**Comment by leios** [comment]
This was merged in latest commit. Thanks again! (sorry for my messy git)

**Pull request closed without merging**
