### PR TITLE
add clojure implementation for bogo sort

### PR DESCRIPTION
**Pull request by earthfail**
I'm starting with the simple stuff

again Mr. @leios if there is anything you want me to contribute tell me. I want this project to succeed

### CODE REVIEW

**Comment by julianschacherpp** [comment]
Hey @earthfail I'am currently adding Clojure to the book.json. So @leios please hold the PR for a second :)

**Comment by leios** [comment]
Not a problem! I was trying to figure out how to get the syntax highlighting to work. It looks like clojure is another C/C++ right now without highlighting? I need to figure out how to fix that...

**Comment by julianschacherpp** [comment]
@leios I'll look into that

**Comment by earthfail** [comment]
thanks, @julianschacherpp  I thought there was something wrong with my browser 
👍

**Comment by leios** [comment]
Hey @earthfail ,

My understanding is that @julianschacherpp had a few smallscale changes and created a pull request for your fork. Once those changes are merged, I'll merge here.

Sorry for any confusion / if my understanding is incorrect! 

Thanks again! =)

**Comment by leios** [comment]
Hey @earthfail thanks for the submission! 

@julianschacherpp, thanks for the help! =)

**Comment by earthfail** [comment]
yeah @julianschacherpp you're the real mvp

**Pull request merged**
