### PR TITLE
switch over to clang-format style

### PR DESCRIPTION
**Pull request by ubsan**
I can add a .clang-format as well;

```
BasedOnStyle: LLVM

AlignAfterOpenBracket: AlwaysBreak
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
PointerAlignment: Left
```

### CODE REVIEW

**Comment by leios** [comment]
Yeah, I guess it makes sense to change the style to something that is easy to maintain. I assume that this is done simply with the `.editorconfig`?

**Comment by ubsan** [comment]
It looks like .editorconfig has been entirely replaced by clang-format in the C++ community; similarly with rustfmt in the Rust community. Is it possible, for languages with formatting tools, to use those instead?

**Comment by leios** [comment]
That seems reasonable and should probably be mentioned in PR #59

**Comment by Butt4cak3** [comment]
A .clang-format file in the repo sounds like a good idea to me.

I briefly read up on clang-format and saw that it's not only used for C++. What I did *not* find, however, is a way to place multiple .clang-format files for multiple languages in the same repository. Is there a way to do this? Would it even make sense or should we just use it for C++ and leave it at that?

**Comment by ubsan** [comment]
@Butt4cak3 I have zero opinion on non-C++ languages. That'd be up to the contributes for those languages.

**Comment by leios** [comment]
Hey @ubsan I assume that this is related to the Issue #60 ? Should I wait for those issues to be resolved before merging?

**Comment by ubsan** [comment]
Oh, it's actually quite trivial.

```
---
Language: Cpp
BasedOnStyle: LLVM

AlignAfterOpenBracket: AlwaysBreak
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
PointerAlignment: Left
---
Language: C
...
---
```

so basically, if people of other languages want to use .clang-format, they can.

@leios I don't think so; it's trivial to add support for other languages once they agree how they're going to format them, and this is blocking me on some other things I'd like to do.

**Comment by leios** [comment]
@ubsan so you would prefer to merge this asap? I'll merge it soon, then. I just wanted to see if anyone else (@Gathros in particular) wanted to discuss the style.

**Comment by ubsan** [comment]
Yep! although I'll add a clang-format to the base directory.

**Comment by ubsan** [comment]
@leios please merge

**Comment by leios** [comment]
Alright. Gathros said he didn't mind the format change earlier, so it should be fine.

**Pull request merged**
