### PR TITLE
Add C# to EuclideanAlgorithmPage

### PR DESCRIPTION
**Pull request by julianschacherpp**

### CODE REVIEW

**Comment by leios** [comment]
Thanks again! You rock!

**Comment by julianschacherpp** [comment]
No problem :D It's nice to code for such a great project.

**Comment by leios** [comment]
=). I think we have most of the foundations built. I'll do some reinforcement this upcoming week and then we can move on to some more fun algorithms!

**Comment by julianschacherpp** [comment]
I'm excited :)

**Pull request merged**
