### PR TITLE
Enhance mult-lang.

### PR DESCRIPTION
**Pull request by julianschacherpp**
Update book.json and mult-lang implementation where needed.

### CODE REVIEW

**Comment by leios** [comment]
Looks good, thanks!

**Comment by julianschacherpp** [comment]
A quick note on how to implement mult-lang in the "new" way:

From now on you need to use the abbreviation of the language you want to implement (look at the first image for reference).
An example of what the new implementation looks like can be found in the second image.
If you need to implement a new language just follow the scheme showed in the first image.

Image 1:
screen shot 2018-01-30 at 02 54 03_book json_edit
Image 2:
screen shot 2018-01-30 at 03 03 10_enhance_mult-lang_old_new_edit

**Comment by leios** [comment]
Yeah, I noticed that you changed the names. I think it's better with the abbreviations. It makes it a little easier for us to remember what's what.

**Comment by julianschacherpp** [comment]
It adds to a uniform look of the AAA, since always the same title gets displayed with the same abbreviation. So typos are caught more easily.

**Pull request merged**
