### PR TITLE
Reordering files and updating book.json

### PR DESCRIPTION
**Pull request by Gathros**

### CODE REVIEW

**Comment by leios** [comment]
Wait, there seems to be a slight problem with the theme-api usage here:
```
{% sample lang="c_cpp" %}
￼  [import:1-4, unindent:"true", lang:"c_cpp"](code/c++/Tree.cpp)
```
It seems like both C and C++ use the same sample language in this PR. The sample languages should be c and cpp for c and c++ respectively, but the `lang` for the importing module should remain `c_cpp`

I feel like that was my fault for not communicating better, sorry!

**Comment by Gathros** [comment]
Oh ok, i'll fix that.

**Comment by Gathros** [comment]
I was right the first time, I got this error after changing it:

```
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `c`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `c`, use default
warn: include-codeblock: unknown language `c`, use default
warn: include-codeblock: unknown language `c`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `c`, use default
warn: include-codeblock: unknown language `cpp`, use default
warn: include-codeblock: unknown language `c`, use default
```

**Comment by leios** [comment]
To be clear: 
```
{% sample lang="c_cpp" %}
￼  [import:1-4, unindent:"true", lang:"c_cpp"](code/c++/Tree.cpp)
```

Should be
```
{% sample lang="cpp" %}
￼  [import:1-4, unindent:"true", lang:"c_cpp"](code/c++/Tree.cpp)

**Comment by Gathros** [comment]
Right, I understand now.

**Comment by leios** [comment]
Thanks again! Sorry for being unclear.

**Comment by Gathros** [comment]
Done, Its fixed now.

**Comment by leios** [comment]
Great! I merged it. Thanks again! =)

**Pull request merged**
