### PR TITLE
Cleaned up "Added Elm code for Euler, with visualization" (#62)

### PR DESCRIPTION
**Pull request by Butt4cak3**
This pull request is a cleand up version of #62. I got the branch up-to-date with master and removed the already merged commits/merge commits. I also changed a bit that we (I think) collectively agreed on, which is that the HTML file is code output and should, for that and other reasons, not be included.

I preserved the original commit author, so that @jiegillet still shows up as the contributor of the code.

### CODE REVIEW

**Comment by jiegillet** [comment]
If we are not using the html, I'd rather not include the full code at all, just the algorithm is enough.

**Comment by leios** [comment]
Alright, we still need more discussion on  this PR. Does it completely replace #62 ?

**Comment by Butt4cak3** [comment]
@Leios Yes. It is the same as the other PR but rebased and with one change.

**Comment by leios** [comment]
Ok, so my understanding is that it's ready to merge?

**Comment by Butt4cak3** [comment]
There's no open discussion about its content, so we should be good. Go ahead, Schloss Boss.

**Comment by leios** [comment]
Cool. Thanks!

**Pull request merged**
