### PR TITLE
mult-lang code-dir

### PR DESCRIPTION
**Pull request by julianschacherpp**
Add mult-lang for the whole fundamental_algorithm/ and code-dir with C# for the whole fundamental_algorithm/ excluding bogo sort.
This provides an example on how to implement both plug-ins in other chapters.

### CODE REVIEW

**Comment by leios** [comment]
Oh, wow. This is a huge change. Seriously, thanks a bunch! I'll merge it soon!

**Comment by julianschacherpp** [comment]
You're welcome :)

**Comment by julianschacherpp** [comment]
Here is an overview of all chapters, mult-lang / code-dir can be implemented in:
[AAA_contents_mult-lang_code-dir.pdf](https://github.com/leios/algorithm-archive/files/1629401/AAA_contents_mult-lang_code-dir.pdf)

Legend for the symbols:
- A filled arrow indicates, that mult-lang / code-dir can be implemented there for sure. 
- A basic arrows indicates, that there's code in chapter and mult-lang / code-dir can get implemented maybe (most likely not).
- A dash indicates mult-lang / code-dir shouldn't or can not be implemented.
- A "ta" with a check behind it indicates, that mult-lang is implemented.
- A "C#" with a check behind it indicates, that code-dir is implemented with C#.

**Comment by leios** [comment]
Haha, wow. That's great! Thanks again! I'm checking the changes now, so it'll be merged at some point today.

**Comment by julianschacherpp** [comment]
Alright, take your time. :)

**Comment by leios** [comment]
Hey @julianschacherpp, I realize you are still working on this and I would love to get my hands on it, but do you want to do more before I merge it? I don't want to step on your toes here and am super appreciative of the work!

**Comment by julianschacherpp** [comment]
You can merge it, if you want, since I’am completely done with this pages/chapter. I planned on providing mult-lang_code-dir for the other chapters as well, but I can easily combine that in other PRs.

**Comment by julianschacherpp** [comment]
If you want to implement mult-lang_code-dir on a page I didn’t implement it on already, write me that on Discord and I don’t work on it, until you finished it, so that I can just add C#, if you’re done.
That way we don’t do double work on a page and you can do progress on the AAA, in a way you like it.

**Comment by leios** [comment]
Alright, sounds good. I'll keep you updated there. Thanks again!

**Comment by julianschacherpp** [comment]
No problem.

**Comment by julianschacherpp** [comment]
No problem.

**Comment by julianschacherpp** [comment]
Accidentally closed the PR. Sorry.

**Comment by ubsan** [comment]
I like this, although I don't like that C# and C++ are done next to each other for the examples. I'd rather settle on one language, and just stick to it throughout. I think I'd prefer C#, since I think it's less complicated/requires less understanding.

**Comment by leios** [comment]
What do you mean, "stick to one language"? C# is not C++.

**Comment by ubsan** [comment]
@leios https://github.com/leios/algorithm-archive/pull/32/files#diff-d7fd75aa4226863d5398ae9e580e8b9dR43 <- this thing.

I think it'd be better to do, like, one language throughout the article, and then each example at the end.

**Comment by leios** [comment]
Ah, I kinda like the fact that the code snippets in the text change depending on the language chosen. I think it allows users to choose the language that makes the most sense to them. There will also be a "pseudocode" option for most articles to go with it.

**Comment by ubsan** [comment]
@leios oh! I didn't know that's what was happening. That's cool!

**Comment by leios** [comment]
Yeah, I just need to go back through and re-write psuedocode for everything and then update the "how to contribute" section when it seems to work. My hope is to get this tested by the end of the week.

**Comment by julianschacherpp** [comment]
@ubsan sorry. I realize I should've explained what the PR/changes is/are about.
This PR implements multiple languages per page (you can see, which pages need to/have implement it in a post of mine above). It also adds a code directory per chapter, so we can just link the code of the codefile in text (the post above shows also, where this is already implemented and where not). I implemented it until now just for C#, since I'm not the best to implement in-text-code (multiple languages) in other languages or create files to populate the code directory with them. (more info is coming later)

**Comment by julianschacherpp** [comment]
The following document provides some useful information on how to implement mult-lang_code-dir:
[multi-lang_code-dir_20180111.pdf](https://github.com/leios/algorithm-archive/files/1634191/multi-lang_code-dir_20180111.pdf)

- [1] shows the functionality of mult-lang
- [2] shows how to implement mult-lang (in-text code, multiple languages)
- [3] shows how to implement code-dir (in-text code in combination with mult-lang & code examples at the bottom of the page)

Here's an example, where you can try out the theme-api plugin (which we use for mult-lang) yourself:
https://developer.gitbook.com/#

**Pull request merged**
